### ISSUE TITLE
Create a nav ( aka nv) shortcut command

### ISSUE THREAD

**Issue by grantkemp** [inviqa/MX_HelperBar#26]
(Enhancement) 
Its annoying to need to use the mouse to do the navigation when we have a much easier way to navigate via the command bar.

Ideally there should be a shortcut key to give focus to the search bar. 
Ideally we should be able to to type `nv` into the bar and get a list of the common admin menu items. 
eg `nv content` will take you to the cms editor
`nv product` will take you to the product catalog list. 
`nv report` will take you to the sales report.

**Comment by alessandrozucca** [comment]
> Ideally we should be able to to type nv into the bar and get a list of the common admin menu items

We could define a list of menu items that we believe are the most important and then allow authorised users to add others in the Admin page

We should also provide a full command for `nv` i.e. 'navigation'. This is similarly to what happens in CLI applications that provides full (`-o`) and long (`--output-file`) arguments

**Comment by grantkemp** [comment]
I think we can make it even quicker - just use "n " (n space) to trigger . 

The navigation should ideally just follow the magento nav and naming terminology.  using the following simple schema
` n <first three letters of Magento Nav Menu> Space <first 5 letters of report> 
eg 
My personal top 6 to illustrate nav schema  
1.`n pro catal` = Products -> catalogue: admin/catalog/product/index/
2. `n sal  order` = Sales Orders: /admin/sales/order/index/
3. `n pag` = Cms Pages : /admin/cms/page/index/
4. `n rep order` = Report-> Orders : /admin/reports/report_sales/sales/
5. `n rep lowst`  = Reports -> Low Stock Report : /admin/reports/report_product/lowstock
6. `n sto config` = Stores -> Config 

What do you think Alessandro?

**Comment by alessandrozucca** [comment]
If we take the first 5 letter we could end up with not unique strings. Take for example the reports:
- Invitations
- Invited Customers

They would both match `n rep invit`

**Comment by grantkemp** [comment]
maybe we replace that shortcut `n ` and replace it with `s ` to replace with common shortcuts. 
we then use the `n ` prefix to auto suggest the full navigation name using an auto completion pattern. 

eg for Invitations and invitated Customers you would type in the top menu option `Reports` and then it would present the drop down with all the sub-reports which the user could use the arrow keys to select ( similar to how code complete works )

**Comment by alessandrozucca** [comment]
@grantkemp the develop branch now has a couple of navigation redirect shortcut commands
- nav cms page
- nav cms block

and more can be added via dependency injections as each shortcut is a magento virtualType

https://github.com/inviqa/MX_HelperBar/blob/develop/src/etc/di.xml#L62-L85

**Comment by grantkemp** [comment]
Thats epic.  We need to update the readme with how to create shortcuts.

**Comment by alessandrozucca** [comment]
@grantkemp PR with readme updates 
https://github.com/inviqa/MX_HelperBar/pull/38

and you can have a preview on github
https://github.com/inviqa/MX_HelperBar/tree/features/readme-updates

**Comment by alessandrozucca** [comment]
This has been implemented, thanks for the idea 👍
