### ISSUE TITLE
Add Google Analytics to the helper bar to help see frequency of usage for backend

### ISSUE THREAD

**Issue by grantkemp** [inviqa/MX_HelperBar#27]
One of the things we noticed is that there are a large variety of users in a typical Magneto backend. 

It would be useful to understand: 

- how many users are using the backend, 
-  what reports they are using?
-  how often? 
- and if there are any errors being produced 

Output: 
This would provide a value that we can create shortcusts for these more common reports. 

Approach: 
- Allow the backend admin to enable Google Analytics in the backend via the helper bar configuration screen,  to have the code appear on all pages in the backend. 
- The magento admin can enter a Google Anayltics UA- code into the backend Helper bar config page and press save to enable it.

**Comment by alessandrozucca** [comment]
It would have been useful information but this functionality can't be added as part of this module. It can be developed separately.
